### ISSUE TITLE
Process Killed

### ISSUE THREAD

**Issue by achalporwal** [whatsplay/whatsapp-play#419]
C:\Users\porwal>wplay -wc
                 __
 _      ______  / /___ ___  __
| | /| / / __ \/ / __ `/ / / /
| |/ |/ / /_/ / / /_/ / /_/ /
|__/|__/ .___/_/\__,_/\__, /
      /_/            /____/

? ***Session Manager***:  Restore a session
? Select a session to try to restore:  Achal
You've to go to whatsapp web and select target manually
You've selected the target named by: +91 ***** *****
Waiting for selector "#app > div > div > div:nth-child(2) > div:last-of-type > span > div > span > div > div > div:first-child > div" failed: timeout 8000ms exceeds.
'NoneType' object is not subscriptable
Process Killed!
Traceback (most recent call last):
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\porwal\AppData\Local\Programs\Python\Python39\Scripts\wplay.exe\__main__.py", line 4, in <module>
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\__main__.py", line 216, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\__main__.py", line 209, in main
    await get_and_match_args(parser)
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\__main__.py", line 165, in get_and_match_args
    await terminal_chat.chat(args.target)
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\terminal_chat.py", line 34, in chat
    target = await target_select.manual_select_target(page)
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\utils\target_select.py", line 20, in manual_select_target
    target_search.__print_complete_target_info(complete_target_info)
  File "c:\users\porwal\appdata\local\programs\python\python39\lib\site-packages\wplay\utils\target_search.py", line 431, in __print_complete_target_info
    for key in complete_target_info.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by rpotter12** [comment]
Hi @achalporwal,
Whatsapp always changes its HTML format every few months. This is error is caused by that only. To fix this we need to change the selector in wplay/utils/helpers.py file. Please open a pull request if you to contribute.

**Comment by rpotter12** [comment]
@achalporwal Please update whatsapp-play with latest pypi package.
